export const SHOW_PROJECT_FORM = 'SHOW_PROJECT_FORM';
export const GET_PROJECTS_LIST = 'GET_PROJECTS_LIST'
export const ADD_PROJECT = 'ADD_PROJECT'
export const FORM_VALIDATE = 'FORM_VALIDATE'
export const SET_SELECTED_PROJECT = 'SET_SELECTED_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const PROJECT_ERROR = 'PROJECT_ERROR'

// TASKS
export const GET_TASKS_PROJECT = 'GET_TASKS_PROJECT'
export const ADD_TASK = 'ADD_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const VALIDATE_TASK = 'VALIDATE_TASK'
export const SET_TASK_SELECTED = 'SET_TASK_SELECTED'

// ALERTS
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

// AUTH
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const LOGIN_SUCESS = 'LOGIN_SUCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const GET_USER = 'GET_USER'
export const SIGN_OUT = 'SIGN_OUT'