export const SHOW_PROJECT_FORM = 'SHOW_PROJECT_FORM';
export const GET_PROJECTS_LIST = 'GET_PROJECTS_LIST'
export const ADD_PROJECT = 'ADD_PROJECT'
export const FORM_VALIDATE = 'FORM_VALIDATE'
export const SET_SELECTED_PROJECT = 'SET_SELECTED_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'

// TASKS
export const GET_TASKS_PROJECT = 'GET_TASKS_PROJECT'
export const ADD_TASK = 'ADD_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const VALIDATE_TASK = 'VALIDATE_TASK'
export const SET_TASK_STATE = 'SET_TASK_STATE'
export const SET_TASK_SELECTED = 'SET_TASK_SELECTED'

// ALERTS
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'