export const SHOW_PROJECT_FORM = 'SHOW_PROJECT_FORM';
export const GET_PROJECTS_LIST = 'GET_PROJECTS_LIST'
export const ADD_PROJECT = 'ADD_PROJECT'
export const FORM_VALIDATE = 'FORM_VALIDATE'
export const SET_SELECTED_PROJECT = 'SET_SELECTED_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'